export enum settingsOptions {
    DISABLE_EMAIL_LOGIN = 'DISABLE_EMAIL_LOGIN',
    DISABLE_PHONE_LOGIN = 'DISABLE_PHONE_LOGIN',
    DISABLE_EMAIL_SIGNUP = 'DISABLE_EMAIL_SIGNUP',
    DISABLE_PHONE_SIGNUP = 'DISABLE_PHONE_SIGNUP',
    ALLOW_INACTIVE_USER_LOGIN = 'ALLOW_INACTIVE_USER_LOGIN',
    ALLOW_UNVERIFIED_PHONE_LOGIN = 'ALLOW_UNVERIFIED_PHONE_LOGIN',
    ALLOW_UNVERIFIED_EMAIL_LOGIN = 'ALLOW_UNVERIFIED_EMAIL_LOGIN',
    ALLOW_EMAIL_TWO_FACTOR_AUTH = 'ALLOW_EMAIL_TWO_FACTOR_AUTH',
    ALLOW_PHONE_TWO_FACTOR_AUTH = 'ALLOW_PHONE_TWO_FACTOR_AUTH',
}
